'batch_size': 16
'valid_ratio': 0.3
'n_epochs': 20
'learning_rate': 0.001
'config_folder': '.\\configs\\model'
'update_mean_std_configs':
- 'test.yaml'
- 'inference.yaml'
'folder_path': '.\\data\\interim\\augmented\\train'
'save_model_path': '.\\models\\model_cnn.pth'